services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"  
    environment:
      - INFLUXDB_ADMIN_USER=igo03
      - INFLUXDB_ADMIN_PASSWORD=igonik2003
      - INFLUXDB_BUCKET=iot_data
      - INFLUXDB_ORG=iot-org
    volumes:
      - influxdb_data:/var/lib/influxdb2  
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"   # port za Grafana web UI
    environment:
      - GF_SECURITY_ADMIN_USER=igo03
      - GF_SECURITY_ADMIN_PASSWORD=igonik2003
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data: